### ISSUE TITLE
Implement basic functionality for initial form

### ISSUE THREAD

**Issue by jmsevold** [jmsevold/book-tracker#4]
- [x] **Step 1**
  Upon button click, send a GET to the google books api and log the results to the console. The array of objects should look like this:

```
{
  thumbnail:
  title:
  pageCount:
}
```

This is the endpoint you want: https://developers.google.com/apis-explorer/?hl=en_US#p/books/v1/books.volumes.list
- [ ] **Step 2**
  After verifying that the API is successfully called upon button click, implement an auto-complete component (such as this https://github.com/moroshko/react-autosuggest) so that each keystroke sends a GET to the API and displays the suggestions below. Bear in mind only the book titles will be needed, not the thumbnail or pageCount. Consider a helper method to map and return only the title.
- [ ] **Step 3**
  Once autocomplete is working, the button click should no longer call the API as before, but instead save the state. Upon saving the state,an additional text input field appears (it would be cool if there was some nifty fade in or slide-down type of animation):
- How many pages can you commit to reading per day?
  Upon entering this info, we now have all the information needed to make further calculations and keep us on track.

**Comment by cacheflow** [comment]
Not sure if autocomplete needs to be done, because to have that working we need a bunch of books to test against. Just checked the google api and it seems like it finds the closest match to the book you've searched for.
